// Bismillah Hir Rahman Nir Raheem
package com.albbiz.map.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage { EN, SQ }

data class AppStrings(
    // General
    val appName: String,
    val save: String,
    val cancel: String,
    val back: String,
    val loading: String,
    val noResults: String,
    val welcomeUser: String,

    // Auth
    val welcomeTitle: String,
    val welcomeDesc: String,
    val getStarted: String,
    val signIn: String,
    val signUp: String,
    val email: String,
    val password: String,
    val confirmPassword: String,
    val logout: String,
    val noAccount: String,
    val haveAccount: String,
    // Map
    val searchPlaceholder: String,
    val addBusiness: String,
    val listView: String,
    val favorites: String,
    val profile: String,
    val communityEvents: String,
    val viewDetailsAndRate: String,
    // Business List
    val directory: String,
    val featured: String,
    val recentlyAdded: String,
    val topRated: String,
    val allBusinesses: String,
    val getDirections: String,
    val nearMe: String,
    // Business Detail
    val recentReviews: String,
    val noReviewsYet: String,
    val writeReview: String,
    val editBusiness: String,
    val upgradePremium: String,
    val viewPlans: String,
    val photos: String,
    val workingHours: String,
    val promotions: String,
    val jobs: String,
    val readMore: String,
    val readLess: String,
    val category: String,
    val verified: String,
    val albanianOwned: String,
    val premium: String,
    val featured2: String,
    val sponsored: String,
    // Profile
    val myProfile: String,
    val personalInformation: String,
    val firstName: String,
    val lastName: String,
    val saveProfile: String,
    val upgradeToPremium: String,
    // Events
    val communityEventsTitle: String,
    val noEventsFound: String,
    val submitEvent: String,
    val eventTitle: String,
    val eventDescription: String,
    val eventDate: String,
    val eventLocation: String,
    val eventWebsite: String,
    val eventCategory: String,
    val addPhoto: String,
    val changePhoto: String,
    val promoted: String,
    val viewEventWebsite: String,
    // Reviews
    val rateThisBusiness: String,
    val tapStarToRate: String,
    val shareExperience: String,
    val submitReview: String,
    val submitting: String,
    // Subscription
    val choosePlan: String,
    val upgradeYourListing: String,
    val currentPlan: String,
    val requestUpgrade: String,
    val requestSponsorship: String,
    val requestFeatured: String,
    val manualPaymentNote: String,
    // Favorites
    val myFavorites: String,
    val noFavoritesYet: String,
    val noSearchResults: String,
    val upgradePremiumTitle: String,

    val firstNameRequired: String,
    val profileSaved: String,
    val profileSaveFailed: String,

    // In AppStrings
    val eventPhotoSection: String,
    val eventDetailsSection: String,
    val eventDateSection: String,
    val eventLocationSection: String,

    val eventTitleRequired: String,
    val eventDescriptionRequired: String,
    val eventLocationRequired: String,
    val eventInvalidDate: String,
    val eventSubmitSuccess: String,
    val eventSubmitFailed: String,
    val submitEventButton: String,

    val writeReviewLabel: String,
    val pleaseSelectRating: String,
    val pleaseWriteReview: String,
    val reviewSubmitted: String,

    val welcomeBack: String,
    val signInToContinue: String,
    val signUpToGetStarted: String,
    val notNow: String,

    val emailRequired: String,
    val passwordRequired: String,
    val passwordsDoNotMatch: String,
    val passwordTooShort: String,

    val registerBusiness: String,
    val requiredInformation: String,
    val businessName: String,
    val locationSection: String,
    val fullAddress: String,
    val latitude: String,
    val longitude: String,
    val pickLocationFromMap: String,
    val contactInformation: String,
    val phoneNumber: String,
    val emailOptional: String,
    val websiteOptional: String,
    val workingHoursSection: String,
    val open247: String,
    val photoOptional: String,
    val photoAdded: String,
    val registering: String,
    val registerBusinessButton: String,
    val businessNameRequired: String,
    val selectCategory: String,
    val descriptionRequired: String,
    val addressRequired: String,
    val phoneRequired: String,
    val validCoordinates: String,
    val businessRegistered: String,
    val cameraPermissionRequired: String,
    val gallery: String,
    val camera: String,
    val choosePhotoSource: String,


)

val EnglishStrings = AppStrings(
    // General
    appName = "MeTont",
    save = "Save",
    cancel = "Cancel",
    back = "Back",
    loading = "Loading...",
    noResults = "No businesses found",
    welcomeUser = "Welcome",
    // Auth
    welcomeTitle = "Welcome to Albanian Business App",
    welcomeDesc = "Register your business, or explore the Albanian business map in your area and beyond.",
    getStarted = "Get Started",
    signIn = "Sign In",
    signUp = "Create Account",
    email = "Email",
    password = "Password",
    confirmPassword = "Confirm Password",
    logout = "Logout",
    noAccount = "Don't have an account? Sign Up",
    haveAccount = "Already have an account? Sign In",
    // Map
    searchPlaceholder = "Search businesses...",
    addBusiness = "Add My Business",
    listView = "List View",
    favorites = "My Favorites",
    profile = "Profile",
    communityEvents = "Community Events",
    viewDetailsAndRate = "View Details & Rate",
    // Business List
    directory = "Directory",
    featured = "Featured Businesses",
    recentlyAdded = "Recently Added",
    topRated = "Top Rated",
    allBusinesses = "All Businesses",
    getDirections = "Get Directions",
    nearMe = "Near Me",
    // Business Detail
    recentReviews = "Recent Reviews",
    noReviewsYet = "No reviews yet. Be the first!",
    writeReview = "Review",
    editBusiness = "Edit",
    upgradePremium = "Upgrade to Premium to unlock contact info, website, photos and more for just \$2.99/month",
    viewPlans = "View Plans",
    photos = "Photos",
    workingHours = "Working Hours",
    promotions = "Promotions & Deals",
    jobs = "Job Postings",
    readMore = "Read more",
    readLess = "Read less",
    category = "Category",
    verified = "Verified",
    albanianOwned = "Albanian Owned",
    premium = "Premium",
    featured2 = "Featured",
    sponsored = "Sponsored",
    // Profile
    myProfile = "My Profile",
    personalInformation = "Personal Information",
    firstName = "First Name",
    lastName = "Last Name",
    saveProfile = "Save Profile",
    upgradeToPremium = "Upgrade to Premium",
    // Events
    communityEventsTitle = "Community Events",
    noEventsFound = "No upcoming events found.",
    submitEvent = "Submit Event",
    eventTitle = "Event Title",
    eventDescription = "Description",
    eventDate = "Event Date",
    eventLocation = "Location Name",
    eventWebsite = "Website URL (Optional)",
    eventCategory = "Category",
    addPhoto = "Add Photo",
    changePhoto = "Change Photo",
    promoted = "PROMOTED",
    viewEventWebsite = "View Event Website",
    // Reviews
    rateThisBusiness = "Rate this business",
    tapStarToRate = "Tap a star to select a rating",
    shareExperience = "Share your experience...",
    submitReview = "Submit Review",
    submitting = "Submitting...",
    // Subscription
    choosePlan = "Choose Your Plan",
    upgradeYourListing = "Upgrade Your Listing",
    currentPlan = "CURRENT",
    requestUpgrade = "Request Upgrade",
    requestSponsorship = "Request Sponsorship",
    requestFeatured = "Request Featured",
    manualPaymentNote = "Payments are currently processed manually. We will contact you within 24 hours of your request.",
    // Favorites
    myFavorites = "My Favorites",
    noFavoritesYet = "You haven't saved any businesses yet.",
    noSearchResults = "No results found",
    upgradePremiumTitle = "Upgrade to Premium",

    // In EnglishStrings
    firstNameRequired = "First name is required",
    profileSaved = "Profile saved!",
    profileSaveFailed = "Failed to save profile",

    // In EnglishStrings
    eventPhotoSection = "Event Photo (Optional)",
    eventDetailsSection = "Event Details",
    eventDateSection = "Event Date *",
    eventLocationSection = "Location & Contact",

    eventTitleRequired = "Event title is required",
    eventDescriptionRequired = "Description is required",
    eventLocationRequired = "Location is required",
    eventInvalidDate = "Please enter a valid date",
    eventSubmitSuccess = "Event submitted successfully!",
    eventSubmitFailed = "Failed to submit event",
    submitEventButton = "Submit Event",

    writeReviewLabel = "Write your review",
    pleaseSelectRating = "Please select a rating",
    pleaseWriteReview = "Please write a review",
    reviewSubmitted = "Review submitted!",

    welcomeBack = "Welcome back!",
    signInToContinue = "Sign in to continue",
    signUpToGetStarted = "Sign up to get started",
    notNow = "Not now",

    emailRequired = "Email is required",
    passwordRequired = "Password is required",
    passwordsDoNotMatch = "Passwords don't match",
    passwordTooShort = "Password must be at least 6 characters",
    registerBusiness = "Register Business",
    requiredInformation = "Required Information",
    businessName = "Business Name *",
    locationSection = "Location *",
    fullAddress = "Full Address *",
    latitude = "Latitude *",
    longitude = "Longitude *",
    pickLocationFromMap = "Pick Location from Map",
    contactInformation = "Contact Information",
    phoneNumber = "Phone Number *",
    emailOptional = "Email (Optional)",
    websiteOptional = "Website (Optional)",
    workingHoursSection = "Working Hours",
    open247 = "Open 24/7",
    photoOptional = "Photo (Optional)",
    photoAdded = "Photo Added (1/1)",
    registering = "Registering...",
    registerBusinessButton = "Register Business",
    businessNameRequired = "Business name is required",
    selectCategory = "Please select a category",
    descriptionRequired = "Description is required",
    addressRequired = "Address is required",
    phoneRequired = "Phone number is required",
    validCoordinates = "Please enter valid coordinates",
    businessRegistered = "Business registered successfully!",
    cameraPermissionRequired = "Camera permission required",
    gallery = "Gallery",
    camera = "Camera",
    choosePhotoSource = "Choose photo source",
    )

val AlbanianStrings = AppStrings(
    // General
    appName = "MeTont",
    save = "Ruaj",
    cancel = "Anulo",
    back = "Kthehu",
    loading = "Duke ngarkuar...",
    noResults = "Nuk u gjet asnjë biznes",
    welcomeUser = "Mirë se vini",
    // Auth
    welcomeTitle = "Mirësevini në MeTont",
    welcomeDesc = "Regjistroni biznesin tuaj, ose eksploroni hartën e bizneseve shqiptare në zonën tuaj dhe më gjerë.",
    getStarted = "Fillo Tani",
    signIn = "Hyr",
    signUp = "Krijo Llogari",
    email = "Email",
    password = "Fjalëkalimi",
    confirmPassword = "Konfirmo Fjalëkalimin",
    logout = "Dil",
    noAccount = "Nuk keni llogari? Regjistrohu",
    haveAccount = "Keni llogari? Hyr",
    // Map
    searchPlaceholder = "Kërko biznese...",
    addBusiness = "Shto Biznesin Tim",
    listView = "Lista",
    favorites = "Të Preferuarat",
    profile = "Profili",
    communityEvents = "Ngjarjet e Komunitetit",
    viewDetailsAndRate = "Shiko Detajet & Vlerëso",
    // Business List
    directory = "Drejtori",
    featured = "Bizneset e Rëndësishme",
    recentlyAdded = "Shtuar Së Fundmi",
    topRated = "Më të Vlerësuarit",
    allBusinesses = "Të Gjitha Bizneset",
    getDirections = "Drejtimet",
    nearMe = "Pranë Meje",
    // Business Detail
    recentReviews = "Vlerësimet e Fundit",
    noReviewsYet = "Asnjë vlerësim ende. Bëhu i pari!",
    writeReview = "Vlerëso",
    editBusiness = "Ndrysho",
    upgradePremium = "Kaloni në Premium për të zhbllokuar kontaktet, faqen dhe fotot për vetëm \$2.99/muaj",
    viewPlans = "Shiko Planet",
    photos = "Foto",
    workingHours = "Orari i Punës",
    promotions = "Promocione dhe Oferta",
    jobs = "Oferta Pune",
    readMore = "Lexo më shumë",
    readLess = "Lexo më pak",
    category = "Kategoria",
    verified = "Verifikuar",
    albanianOwned = "Pronë Shqiptare",
    premium = "Premium",
    featured2 = "I Veçuar",
    sponsored = "Sponsorizuar",
    // Profile
    myProfile = "Profili Im",
    personalInformation = "Informacioni Personal",
    firstName = "Emri",
    lastName = "Mbiemri",
    saveProfile = "Ruaj Profilin",
    upgradeToPremium = "Kalo në Premium",
    // Events
    communityEventsTitle = "Ngjarjet e Komunitetit",
    noEventsFound = "Nuk u gjetën ngjarje të ardhshme.",
    submitEvent = "Dërgo Ngjarjen",
    eventTitle = "Titulli i Ngjarjes",
    eventDescription = "Përshkrimi",
    eventDate = "Data e Ngjarjes",
    eventLocation = "Emri i Vendit",
    eventWebsite = "URL e Faqes (Opsionale)",
    eventCategory = "Kategoria",
    addPhoto = "Shto Foto",
    changePhoto = "Ndrysho Foton",
    promoted = "PROMOVUAR",
    viewEventWebsite = "Shiko Faqen e Ngjarjes",
    // Reviews
    rateThisBusiness = "Vlerëso këtë biznes",
    tapStarToRate = "Trokitni një yll për të vlerësuar",
    shareExperience = "Ndani përvojën tuaj...",
    submitReview = "Dërgo Vlerësimin",
    submitting = "Duke dërguar...",
    // Subscription
    choosePlan = "Zgjidhni Planin Tuaj",
    upgradeYourListing = "Përmirësoni Listimin Tuaj",
    currentPlan = "AKTUAL",
    requestUpgrade = "Kërkoni Përmirësim",
    requestSponsorship = "Kërkoni Sponsorizim",
    requestFeatured = "Kërkoni të Veçohet",
    manualPaymentNote = "Pagesat aktualisht procesohen manualisht. Do t'ju kontaktojmë brenda 24 orëve.",
    // Favorites
    myFavorites = "Të Preferuarat e Mia",
    noFavoritesYet = "Nuk keni ruajtur asnjë biznes ende.",
    noSearchResults = "Nuk u gjetën rezultate",
    upgradePremiumTitle = "Kalo në Premium",


    // In AlbanianStrings
    firstNameRequired = "Emri është i detyrueshëm",
    profileSaved = "Profili u ruajt!",
    profileSaveFailed = "Dështoi ruajtja e profilit",

    // In AlbanianStrings
    eventPhotoSection = "Foto e Ngjarjes (Opsionale)",
    eventDetailsSection = "Detajet e Ngjarjes",
    eventDateSection = "Data e Ngjarjes *",
    eventLocationSection = "Vendndodhja & Kontakti",

    eventTitleRequired = "Titulli i ngjarjes është i detyrueshëm",
    eventDescriptionRequired = "Përshkrimi është i detyrueshëm",
    eventLocationRequired = "Vendndodhja është e detyrueshme",
    eventInvalidDate = "Ju lutemi vendosni një datë të vlefshme",
    eventSubmitSuccess = "Ngjarja u dërgua me sukses!",
    eventSubmitFailed = "Dështoi dërgimi i ngjarjes",
    submitEventButton = "Dërgo Ngjarjen",

    writeReviewLabel = "Shkruaj vlerësimin tuaj",
    pleaseSelectRating = "Ju lutemi zgjidhni një vlerësim",
    pleaseWriteReview = "Ju lutemi shkruani një vlerësim",
    reviewSubmitted = "Vlerësimi u dërgua!",

    welcomeBack = "Mirësevini!",
    signInToContinue = "Hyni për të vazhduar",
    signUpToGetStarted = "Regjistrohu për të filluar",
    notNow = "Jo tani",

    emailRequired = "Email është i detyrueshëm",
    passwordRequired = "Fjalëkalimi është i detyrueshëm",
    passwordsDoNotMatch = "Fjalëkalimet nuk përputhen",
    passwordTooShort = "Fjalëkalimi duhet të ketë të paktën 6 karaktere",

    registerBusiness = "Regjistro Biznesin",
    requiredInformation = "Informacioni i Detyrueshëm",
    businessName = "Emri i Biznesit *",
    locationSection = "Vendndodhja *",
    fullAddress = "Adresa e Plotë *",
    latitude = "Gjerësia *",
    longitude = "Gjatësia *",
    pickLocationFromMap = "Zgjidhni Vendndodhjen nga Harta",
    contactInformation = "Informacioni i Kontaktit",
    phoneNumber = "Numri i Telefonit *",
    emailOptional = "Email (Opsional)",
    websiteOptional = "Faqja Web (Opsionale)",
    workingHoursSection = "Orari i Punës",
    open247 = "Hapur 24/7",
    photoOptional = "Foto (Opsionale)",
    photoAdded = "Foto u Shtua (1/1)",
    registering = "Duke Regjistruar...",
    registerBusinessButton = "Regjistro Biznesin",
    businessNameRequired = "Emri i biznesit është i detyrueshëm",
    selectCategory = "Ju lutemi zgjidhni një kategori",
    descriptionRequired = "Përshkrimi është i detyrueshëm",
    addressRequired = "Adresa është e detyrueshme",
    phoneRequired = "Numri i telefonit është i detyrueshëm",
    validCoordinates = "Ju lutemi vendosni koordinata të vlefshme",
    businessRegistered = "Biznesi u regjistrua me sukses!",
    cameraPermissionRequired = "Leja e kamerës është e nevojshme",
    gallery = "Galeria",
    camera = "Kamera",
    choosePhotoSource = "Zgjidhni burimin e fotos",
    )

val LocalAppStrings = staticCompositionLocalOf { EnglishStrings }

@Composable
fun ProvideAppStrings(language: AppLanguage, content: @Composable () -> Unit) {
    val strings = if (language == AppLanguage.SQ) AlbanianStrings else EnglishStrings
    CompositionLocalProvider(LocalAppStrings provides strings) {
        content()
    }
}