// Bismillah Hir Rahman Nir Raheem
package com.albbiz.map.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.staticCompositionLocalOf

enum class AppLanguage { EN, SQ }

data class AppStrings(
    // General
    val appName: String,
    val save: String,
    val cancel: String,
    val back: String,
    val loading: String,
    val noResults: String,
    val welcomeUser: String,

    // Auth
    val welcomeTitle: String,
    val welcomeDesc: String,
    val getStarted: String,
    val signIn: String,
    val signUp: String,
    val email: String,
    val password: String,
    val confirmPassword: String,
    val logout: String,
    val noAccount: String,
    val haveAccount: String,
    val forgotPassword: String,
    val resetPasswordTitle: String,
    val resetPasswordDescription: String,
    val sendResetLink: String,
    val resetEmailSent: String,
    val continueWithGoogle: String,
    val continueWithApple: String,
    // Map
    val searchPlaceholder: String,
    val addBusiness: String,
    val listView: String,
    val favorites: String,
    val profile: String,
    val communityEvents: String,
    val viewDetailsAndRate: String,
    // Business List
    val directory: String,
    val featured: String,
    val recentlyAdded: String,
    val topRated: String,
    val allBusinesses: String,
    val getDirections: String,
    val nearMe: String,
    // Business Detail
    val recentReviews: String,
    val noReviewsYet: String,
    val writeReview: String,
    val editBusiness: String,
    val upgradePremium: String,
    val viewPlans: String,
    val photos: String,
    val workingHours: String,
    val promotions: String,
    val jobs: String,
    val readMore: String,
    val readLess: String,
    val category: String,
    val verified: String,
    val albanianOwned: String,
    val premium: String,
    val featured2: String,
    val sponsored: String,
    // Profile
    val myProfile: String,
    val personalInformation: String,
    val firstName: String,
    val lastName: String,
    val saveProfile: String,
    val upgradeToPremium: String,
    // Events
    val communityEventsTitle: String,
    val noEventsFound: String,
    val submitEvent: String,
    val eventTitle: String,
    val eventDescription: String,
    val eventDate: String,
    val eventLocation: String,
    val eventWebsite: String,
    val eventCategory: String,
    val addPhoto: String,
    val changePhoto: String,
    val promoted: String,
    val viewEventWebsite: String,
    // Reviews
    val rateThisBusiness: String,
    val tapStarToRate: String,
    val shareExperience: String,
    val submitReview: String,
    val submitting: String,
    // Subscription
    val choosePlan: String,
    val upgradeYourListing: String,
    val currentPlan: String,
    val requestUpgrade: String,
    val requestSponsorship: String,
    val requestFeatured: String,
    val manualPaymentNote: String,
    // Favorites
    val myFavorites: String,
    val noFavoritesYet: String,
    val myBusinesses: String,
    val noBusinessesYet: String,
    val noBusinessesYetSubtitle: String,
    val myBusinessesSubtitle: String,
    val myEvents: String,
    val noEventsYet: String,
    val noEventsYetSubtitle: String,
    val myEventsSubtitle: String,
    val deleteEvent: String,
    val deleteEventConfirmTitle: String,
    val deleteEventConfirmMessage: String,
    val eventDeleted: String,
    val eventDeleteFailed: String,
    val noSearchResults: String,
    val upgradePremiumTitle: String,

    val firstNameRequired: String,
    val profileSaved: String,
    val profileSaveFailed: String,

    // In AppStrings
    val eventPhotoSection: String,
    val eventDetailsSection: String,
    val eventDateSection: String,
    val eventLocationSection: String,

    val eventTitleRequired: String,
    val eventDescriptionRequired: String,
    val eventLocationRequired: String,
    val eventInvalidDate: String,
    val eventSubmitSuccess: String,
    val eventSubmitFailed: String,
    val submitEventButton: String,

    val writeReviewLabel: String,
    val pleaseSelectRating: String,
    val pleaseWriteReview: String,
    val reviewSubmitted: String,

    val welcomeBack: String,
    val signInToContinue: String,
    val signUpToGetStarted: String,
    val notNow: String,

    val emailRequired: String,
    val passwordRequired: String,
    val passwordsDoNotMatch: String,
    val passwordTooShort: String,

    val registerBusiness: String,
    val requiredInformation: String,
    val businessName: String,
    val locationSection: String,
    val fullAddress: String,
    val cityLabel: String,
    val countryLabel: String,
    val cityRequired: String,
    val locatingAddress: String,
    val geocodeFailed: String,
    val latitude: String,
    val longitude: String,
    val pickLocationFromMap: String,
    val contactInformation: String,
    val phoneNumber: String,
    val emailOptional: String,
    val websiteOptional: String,
    val workingHoursSection: String,
    val open247: String,
    val photoOptional: String,
    val photoAdded: String,
    val registering: String,
    val registerBusinessButton: String,
    val businessNameRequired: String,
    val selectCategory: String,
    val descriptionRequired: String,
    val addressRequired: String,
    val phoneRequired: String,
    val validCoordinates: String,
    val businessRegistered: String,
    val cameraPermissionRequired: String,
    val gallery: String,
    val camera: String,
    val choosePhotoSource: String,

    // Generic dialog buttons
    val ok: String,
    val confirm: String,
    val openButton: String,

    // Time picker / working hours
    val hoursOpenLabel: String,
    val hoursCloseLabel: String,

    // Add Event date fields
    val dayLabel: String,
    val dayPlaceholder: String,
    val monthLabel: String,
    val monthPlaceholder: String,
    val yearLabel: String,
    val yearPlaceholder: String,
    val eventStartTimeLabel: String,

    // Edit Business screen
    val basicInformationSection: String,
    val locationSectionShort: String,
    val saveChanges: String,
    val businessUpdatedSuccess: String,
    val categoryRequiredLabel: String,
    val descriptionRequiredLabel: String,
    val photoLimitReached: String,
    val addJobPostingTitle: String,
    val jobTitleLabel: String,
    val jobTypeLabel: String,
    val jobSalaryLabel: String,
    val jobSalaryPlaceholder: String,
    val addJobButton: String,
    val jobTitleDescRequired: String,
    val addPromotionTitle: String,
    val promotionTitleLabel: String,

    // Add Story screen
    val addStoryTitle: String,
    val addPhotosButton: String,
    val captionPlaceholder: String,
    val storyLocationPlaceholder: String,
    val postStory: String,

    // Admin screen
    val importSampleBusinesses: String,
    val approveClaimTitle: String,
    val approveClaimMessage: String,
    val approve: String,
    val rejectClaimTitle: String,
    val rejectClaimMessage: String,
    val reject: String,

    // Business detail screen
    val writeReplyPlaceholder: String,
    val noLocationSetToast: String,
    val googleMapsNotInstalled: String,

    // Business list screen
    val applyFilters: String,
    val allFilterOption: String,

    // Jobs screen
    val viewProfile: String,
    val jobsEmptyTitle: String,
    val jobsEmptySubtitle: String,

    // Map / home screen
    val appTagline: String,
    val viewFullProfile: String,
    val noBusinessesNearYou: String,
    val appGrowingMessage: String,
    val communityAnnouncements: String,
    val noUpcomingEventsShort: String,
    val mostFavoritedWorldwide: String,
    val noBusinessesYetHome: String,

    // Story viewer
    val viewBusiness: String,
    val couldntOpenMaps: String,

    // Events screen
    val couldntOpenLink: String,

    // Reviews
    val loginRequiredForReview: String,

    // Subscription
    val freeTierName: String,

    // Edit Business screen (additional)
    val editBusinessTitle: String,
    val savingLabel: String,
    val promotionsEmptyTitle: String,
    val closedLabel: String,

    // Subscription screen (plan details)
    val upgradeTitleTemplate: String,
    val subscriptionHeaderSubtitle: String,
    val perMonth: String,
    val forever: String,
    val currentPlanButton: String,
    val notAvailableDash: String,
    val sendUpgradeRequest: String,
    val sendFeaturedRequest: String,
    val sendSponsorshipRequest: String,
    val planFeatureNameCategory: String,
    val planFeatureLocationOnMap: String,
    val planFeature100CharDesc: String,
    val planFeature1Photo: String,
    val planFeaturePhoneNumber: String,
    val planFeatureEmailWebsite: String,
    val planFeatureExtendedDesc: String,
    val planFeatureHoursOfOperation: String,
    val planFeaturePremiumBadge: String,
    val planFeatureUp6Photos: String,
    val planFeatureEverythingPremium: String,
    val planFeatureUp10Photos: String,
    val planFeatureFeaturedBadge: String,
    val planFeatureFeaturedDiscoveryRow: String,
    val planFeatureHighlightedListView: String,
    val planFeatureUp14Photos: String,
    val planFeatureHighlightedMapPin: String,
    val planFeatureTopSearchResults: String,
    val planFeatureSponsoredBadge: String,
    val planFeatureFeaturedDiscoverySection: String,
    val planFeaturePriorityCustomerSupport: String,

    // Admin screen (additional)
    val pendingClaimRequests: String,
    val noPendingClaims: String,
    val allClaimsProcessed: String,
    val pendingCountLabel: String,

    // Exception/error messages surfaced from ViewModels and Repositories (no
    // Compose context there, so these are looked up via CurrentLanguage.strings()
    // instead of LocalAppStrings). The raw SDK/Firebase exception text appended
    // after some of these (e.message) can't be localized — it comes from Google's
    // libraries in English regardless of app language.
    val mustBeLoggedInToAddBusiness: String,
    val reviewNotFound: String,
    val alreadyReportedReview: String,
    val replyNotFound: String,
    val reviewReportedSuccess: String,
    val failedToAddBusinessPrefix: String,
    val failedToUploadImagesPrefix: String,
    val unexpectedErrorPrefix: String,
    val failedToUploadPhotos: String,
    val failedToUpdateBusiness: String,
    val errorLoadingClaimsPrefix: String,
    val failedToApprovePrefix: String,
    val failedToRejectPrefix: String,
    val importFailedPrefix: String,
    val claimApprovedTemplate: String,
    val claimRejectedMsg: String,
    val importSuccessTemplate: String,
    val mustBeLoggedInToPostStory: String,
    val addAtLeastOnePhoto: String,
    val maxPhotosPerStory: String,
    val failedToPostStoryFallback: String,
)

val EnglishStrings = AppStrings(
    // General
    appName = "MeTont",
    save = "Save",
    cancel = "Cancel",
    back = "Back",
    loading = "Loading...",
    noResults = "No businesses found",
    welcomeUser = "Welcome",
    // Auth
    welcomeTitle = "Welcome to Albanian Business App",
    welcomeDesc = "Register your business, or explore the Albanian business map in your area and beyond.",
    getStarted = "Get Started",
    signIn = "Sign In",
    signUp = "Create Account",
    email = "Email",
    password = "Password",
    confirmPassword = "Confirm Password",
    logout = "Logout",
    noAccount = "Don't have an account? Sign Up",
    haveAccount = "Already have an account? Sign In",
    forgotPassword = "Forgot password?",
    resetPasswordTitle = "Reset Password",
    resetPasswordDescription = "Enter your email and we'll send you a link to reset your password.",
    sendResetLink = "Send Reset Link",
    resetEmailSent = "Password reset email sent! Check your inbox.",
    continueWithGoogle = "Continue with Google",
    continueWithApple = "Continue with Apple",
    // Map
    searchPlaceholder = "Search businesses...",
    addBusiness = "Add My Business",
    listView = "List View",
    favorites = "My Favorites",
    profile = "Profile",
    communityEvents = "Community Events",
    viewDetailsAndRate = "View Details & Rate",
    // Business List
    directory = "Directory",
    featured = "Featured Businesses",
    recentlyAdded = "Recently Added",
    topRated = "Top Rated",
    allBusinesses = "All Businesses",
    getDirections = "Get Directions",
    nearMe = "Near Me",
    // Business Detail
    recentReviews = "Recent Reviews",
    noReviewsYet = "No reviews yet. Be the first!",
    writeReview = "Review",
    editBusiness = "Edit",
    upgradePremium = "Upgrade to Premium to unlock contact info, website, photos and more for just \$2.99/month",
    viewPlans = "View Plans",
    photos = "Photos",
    workingHours = "Working Hours",
    promotions = "Promotions & Deals",
    jobs = "Job Postings",
    readMore = "Read more",
    readLess = "Read less",
    category = "Category",
    verified = "Verified",
    albanianOwned = "Albanian Owned",
    premium = "Premium",
    featured2 = "Featured",
    sponsored = "Sponsored",
    // Profile
    myProfile = "My Profile",
    personalInformation = "Personal Information",
    firstName = "First Name",
    lastName = "Last Name",
    saveProfile = "Save Profile",
    upgradeToPremium = "Upgrade to Premium",
    // Events
    communityEventsTitle = "Community Events",
    noEventsFound = "No upcoming events found.",
    submitEvent = "Submit Event",
    eventTitle = "Event Title",
    eventDescription = "Description",
    eventDate = "Event Date",
    eventLocation = "Location Name",
    eventWebsite = "Website URL (Optional)",
    eventCategory = "Category",
    addPhoto = "Add Photo",
    changePhoto = "Change Photo",
    promoted = "PROMOTED",
    viewEventWebsite = "View Event Website",
    // Reviews
    rateThisBusiness = "Rate this business",
    tapStarToRate = "Tap a star to select a rating",
    shareExperience = "Share your experience...",
    submitReview = "Submit Review",
    submitting = "Submitting...",
    // Subscription
    choosePlan = "Choose Your Plan",
    upgradeYourListing = "Upgrade Your Listing",
    currentPlan = "CURRENT",
    requestUpgrade = "Request Upgrade",
    requestSponsorship = "Request Sponsorship",
    requestFeatured = "Request Featured",
    manualPaymentNote = "Payments are currently processed manually. We will contact you within 24 hours of your request.",
    // Favorites
    myFavorites = "My Favorites",
    noFavoritesYet = "You haven't saved any businesses yet.",
    myBusinesses = "My Businesses",
    noBusinessesYet = "You don't have any businesses yet",
    noBusinessesYetSubtitle = "Add your business to reach more customers",
    myBusinessesSubtitle = "Manage your business listings",
    myEvents = "My Events",
    noEventsYet = "You don't have any events yet",
    noEventsYetSubtitle = "Submit an event to reach more people",
    myEventsSubtitle = "Manage your submitted events",
    deleteEvent = "Delete Event",
    deleteEventConfirmTitle = "Delete this event?",
    deleteEventConfirmMessage = "This will permanently remove the event. This action cannot be undone.",
    eventDeleted = "Event deleted",
    eventDeleteFailed = "Failed to delete event",
    noSearchResults = "No results found",
    upgradePremiumTitle = "Upgrade to Premium",

    // In EnglishStrings
    firstNameRequired = "First name is required",
    profileSaved = "Profile saved!",
    profileSaveFailed = "Failed to save profile",

    // In EnglishStrings
    eventPhotoSection = "Event Photo (Optional)",
    eventDetailsSection = "Event Details",
    eventDateSection = "Event Date *",
    eventLocationSection = "Location & Contact",

    eventTitleRequired = "Event title is required",
    eventDescriptionRequired = "Description is required",
    eventLocationRequired = "Location is required",
    eventInvalidDate = "Please enter a valid date",
    eventSubmitSuccess = "Event submitted successfully!",
    eventSubmitFailed = "Failed to submit event",
    submitEventButton = "Submit Event",

    writeReviewLabel = "Write your review",
    pleaseSelectRating = "Please select a rating",
    pleaseWriteReview = "Please write a review",
    reviewSubmitted = "Review submitted!",

    welcomeBack = "Welcome back!",
    signInToContinue = "Sign in to continue",
    signUpToGetStarted = "Sign up to get started",
    notNow = "Not now",

    emailRequired = "Email is required",
    passwordRequired = "Password is required",
    passwordsDoNotMatch = "Passwords don't match",
    passwordTooShort = "Password must be at least 8 characters",
    registerBusiness = "Register Business",
    requiredInformation = "Required Information",
    businessName = "Business Name *",
    locationSection = "Location *",
    fullAddress = "Full Address *",
    cityLabel = "City *",
    countryLabel = "Country *",
    cityRequired = "City is required",
    locatingAddress = "Finding coordinates…",
    geocodeFailed = "Couldn't find that address — please check it's correct",
    latitude = "Latitude *",
    longitude = "Longitude *",
    pickLocationFromMap = "Pick Location from Map",
    contactInformation = "Contact Information",
    phoneNumber = "Phone Number *",
    emailOptional = "Email (Optional)",
    websiteOptional = "Website (Optional)",
    workingHoursSection = "Working Hours",
    open247 = "Open 24/7",
    photoOptional = "Photo (Optional)",
    photoAdded = "Photo Added (1/1)",
    registering = "Registering...",
    registerBusinessButton = "Register Business",
    businessNameRequired = "Business name is required",
    selectCategory = "Please select a category",
    descriptionRequired = "Description is required",
    addressRequired = "Address is required",
    phoneRequired = "Phone number is required",
    validCoordinates = "Please enter valid coordinates",
    businessRegistered = "Business registered successfully!",
    cameraPermissionRequired = "Camera permission required",
    gallery = "Gallery",
    camera = "Camera",
    choosePhotoSource = "Choose photo source",

    // Generic dialog buttons
    ok = "OK",
    confirm = "Confirm",
    openButton = "Open",

    // Time picker / working hours
    hoursOpenLabel = "Open",
    hoursCloseLabel = "Close",

    // Add Event date fields
    dayLabel = "Day",
    dayPlaceholder = "DD",
    monthLabel = "Month",
    monthPlaceholder = "MM",
    yearLabel = "Year",
    yearPlaceholder = "YYYY",
    eventStartTimeLabel = "Start time",

    // Edit Business screen
    basicInformationSection = "Basic Information",
    locationSectionShort = "Location",
    saveChanges = "Save Changes",
    businessUpdatedSuccess = "Business updated successfully!",
    categoryRequiredLabel = "Category *",
    descriptionRequiredLabel = "Description *",
    photoLimitReached = "Photo limit reached for your plan",
    addJobPostingTitle = "Add Job Posting",
    jobTitleLabel = "Job Title *",
    jobTypeLabel = "Job Type *",
    jobSalaryLabel = "Salary (Optional)",
    jobSalaryPlaceholder = "e.g. \$1,500/month",
    addJobButton = "Add Job",
    jobTitleDescRequired = "Title and description are required",
    addPromotionTitle = "Add Promotion",
    promotionTitleLabel = "Promotion Title *",

    // Add Story screen
    addStoryTitle = "Add Story",
    addPhotosButton = "Add Photos",
    captionPlaceholder = "Write a caption...",
    storyLocationPlaceholder = "e.g. Tirana, Albania",
    postStory = "Post Story",

    // Admin screen
    importSampleBusinesses = "Import Sample Businesses",
    approveClaimTitle = "Approve Claim",
    approveClaimMessage = "Are you sure you want to approve %1\$s's claim for \"%2\$s\"? This will transfer ownership and verify the business.",
    approve = "Approve",
    rejectClaimTitle = "Reject Claim",
    rejectClaimMessage = "Are you sure you want to reject this claim request from %1\$s?",
    reject = "Reject",

    // Business detail screen
    writeReplyPlaceholder = "Write a reply...",
    noLocationSetToast = "No location set for this business",
    googleMapsNotInstalled = "Google Maps isn't installed",

    // Business list screen
    applyFilters = "Apply Filters",
    allFilterOption = "All",

    // Jobs screen
    viewProfile = "View Profile",
    jobsEmptyTitle = "No job postings yet",
    jobsEmptySubtitle = "Businesses that are hiring will show up here",

    // Map / home screen
    appTagline = "Albanian Business Directory",
    viewFullProfile = "View Full Profile",
    noBusinessesNearYou = "No businesses near you yet",
    appGrowingMessage = "MeTont is growing — check back soon!",
    communityAnnouncements = "Community Announcements",
    noUpcomingEventsShort = "No upcoming events right now",
    mostFavoritedWorldwide = "Most Favorited Worldwide",
    noBusinessesYetHome = "No businesses yet",

    // Story viewer
    viewBusiness = "View Business",
    couldntOpenMaps = "Couldn't open maps",

    // Events screen
    couldntOpenLink = "Couldn't open that link",

    // Reviews
    loginRequiredForReview = "You must be logged in to submit a review",

    // Subscription
    freeTierName = "Free",

    // Edit Business screen (additional)
    editBusinessTitle = "Edit Business",
    savingLabel = "Saving...",
    promotionsEmptyTitle = "No promotions yet.",
    closedLabel = "Closed",

    // Subscription screen (plan details)
    upgradeTitleTemplate = "Upgrade \"%1\$s\"",
    subscriptionHeaderSubtitle = "Help your business stand out in the Albanian community",
    perMonth = "per month",
    forever = "forever",
    currentPlanButton = "Current Plan",
    notAvailableDash = "—",
    sendUpgradeRequest = "Send upgrade request",
    sendFeaturedRequest = "Send featured request",
    sendSponsorshipRequest = "Send sponsorship request",
    planFeatureNameCategory = "Business name & category",
    planFeatureLocationOnMap = "Location on map",
    planFeature100CharDesc = "100 character description",
    planFeature1Photo = "1 photo",
    planFeaturePhoneNumber = "Phone number",
    planFeatureEmailWebsite = "Email & website",
    planFeatureExtendedDesc = "Extended description",
    planFeatureHoursOfOperation = "Hours of operation",
    planFeaturePremiumBadge = "Premium badge",
    planFeatureUp6Photos = "Up to 6 photos",
    planFeatureEverythingPremium = "Everything in Premium",
    planFeatureUp10Photos = "Up to 10 photos",
    planFeatureFeaturedBadge = "Featured badge",
    planFeatureFeaturedDiscoveryRow = "Featured in discovery row",
    planFeatureHighlightedListView = "Highlighted in list view",
    planFeatureUp14Photos = "Up to 14 photos",
    planFeatureHighlightedMapPin = "Highlighted map pin",
    planFeatureTopSearchResults = "Top of search results",
    planFeatureSponsoredBadge = "Sponsored badge",
    planFeatureFeaturedDiscoverySection = "Featured in discovery section",
    planFeaturePriorityCustomerSupport = "Priority customer support",

    // Admin screen (additional)
    pendingClaimRequests = "Pending Claim Requests",
    noPendingClaims = "No pending claims!",
    allClaimsProcessed = "All claim requests have been processed.",
    pendingCountLabel = "pending",

    // Exception/error messages
    mustBeLoggedInToAddBusiness = "You must be logged in to add a business",
    reviewNotFound = "Review not found",
    alreadyReportedReview = "You have already reported this review",
    replyNotFound = "Reply not found",
    reviewReportedSuccess = "Review reported successfully",
    failedToAddBusinessPrefix = "Failed to add business",
    failedToUploadImagesPrefix = "Failed to upload images",
    unexpectedErrorPrefix = "Unexpected error",
    failedToUploadPhotos = "Failed to upload photos",
    failedToUpdateBusiness = "Failed to update business",
    errorLoadingClaimsPrefix = "Error loading claims",
    failedToApprovePrefix = "Failed to approve",
    failedToRejectPrefix = "Failed to reject",
    importFailedPrefix = "Import failed",
    claimApprovedTemplate = "Claim approved — %1\$s is now owned by %2\$s",
    claimRejectedMsg = "Claim rejected",
    importSuccessTemplate = "Successfully imported %1\$d businesses!",
    mustBeLoggedInToPostStory = "You must be logged in to post a story",
    addAtLeastOnePhoto = "Please add at least one photo",
    maxPhotosPerStory = "Maximum 10 photos per story",
    failedToPostStoryFallback = "Failed to post story",
    )

val AlbanianStrings = AppStrings(
    // General
    appName = "MeTont",
    save = "Ruaj",
    cancel = "Anulo",
    back = "Kthehu",
    loading = "Duke ngarkuar...",
    noResults = "Nuk u gjet asnjë biznes",
    welcomeUser = "Mirë se vini",
    // Auth
    welcomeTitle = "Mirësevini në MeTont",
    welcomeDesc = "Regjistroni biznesin tuaj, ose eksploroni hartën e bizneseve shqiptare në zonën tuaj dhe më gjerë.",
    getStarted = "Fillo Tani",
    signIn = "Hyr",
    signUp = "Krijo Llogari",
    email = "Email",
    password = "Fjalëkalimi",
    confirmPassword = "Konfirmo Fjalëkalimin",
    logout = "Dil",
    noAccount = "Nuk keni llogari? Regjistrohu",
    haveAccount = "Keni llogari? Hyr",
    forgotPassword = "Keni harruar fjalëkalimin?",
    resetPasswordTitle = "Rivendos Fjalëkalimin",
    resetPasswordDescription = "Shkruani email-in tuaj dhe ne do t'ju dërgojmë një lidhje për të rivendosur fjalëkalimin.",
    sendResetLink = "Dërgo Lidhjen",
    resetEmailSent = "Email-i për rivendosjen e fjalëkalimit u dërgua! Kontrolloni inbox-in tuaj.",
    continueWithGoogle = "Vazhdo me Google",
    continueWithApple = "Vazhdo me Apple",
    // Map
    searchPlaceholder = "Kërko biznese...",
    addBusiness = "Shto Biznesin Tim",
    listView = "Lista",
    favorites = "Të Preferuarat",
    profile = "Profili",
    communityEvents = "Ngjarjet e Komunitetit",
    viewDetailsAndRate = "Shiko Detajet & Vlerëso",
    // Business List
    directory = "Drejtori",
    featured = "Bizneset e Rëndësishme",
    recentlyAdded = "Shtuar Së Fundmi",
    topRated = "Më të Vlerësuarit",
    allBusinesses = "Të Gjitha Bizneset",
    getDirections = "Drejtimet",
    nearMe = "Pranë Meje",
    // Business Detail
    recentReviews = "Vlerësimet e Fundit",
    noReviewsYet = "Asnjë vlerësim ende. Bëhu i pari!",
    writeReview = "Vlerëso",
    editBusiness = "Ndrysho",
    upgradePremium = "Kaloni në Premium për të zhbllokuar kontaktet, faqen dhe fotot për vetëm \$2.99/muaj",
    viewPlans = "Shiko Planet",
    photos = "Foto",
    workingHours = "Orari i Punës",
    promotions = "Promocione dhe Oferta",
    jobs = "Oferta Pune",
    readMore = "Lexo më shumë",
    readLess = "Lexo më pak",
    category = "Kategoria",
    verified = "Verifikuar",
    albanianOwned = "Pronë Shqiptare",
    premium = "Premium",
    featured2 = "I Veçuar",
    sponsored = "Sponsorizuar",
    // Profile
    myProfile = "Profili Im",
    personalInformation = "Informacioni Personal",
    firstName = "Emri",
    lastName = "Mbiemri",
    saveProfile = "Ruaj Profilin",
    upgradeToPremium = "Kalo në Premium",
    // Events
    communityEventsTitle = "Ngjarjet e Komunitetit",
    noEventsFound = "Nuk u gjetën ngjarje të ardhshme.",
    submitEvent = "Dërgo Ngjarjen",
    eventTitle = "Titulli i Ngjarjes",
    eventDescription = "Përshkrimi",
    eventDate = "Data e Ngjarjes",
    eventLocation = "Emri i Vendit",
    eventWebsite = "URL e Faqes (Opsionale)",
    eventCategory = "Kategoria",
    addPhoto = "Shto Foto",
    changePhoto = "Ndrysho Foton",
    promoted = "PROMOVUAR",
    viewEventWebsite = "Shiko Faqen e Ngjarjes",
    // Reviews
    rateThisBusiness = "Vlerëso këtë biznes",
    tapStarToRate = "Trokitni një yll për të vlerësuar",
    shareExperience = "Ndani përvojën tuaj...",
    submitReview = "Dërgo Vlerësimin",
    submitting = "Duke dërguar...",
    // Subscription
    choosePlan = "Zgjidhni Planin Tuaj",
    upgradeYourListing = "Përmirësoni Listimin Tuaj",
    currentPlan = "AKTUAL",
    requestUpgrade = "Kërkoni Përmirësim",
    requestSponsorship = "Kërkoni Sponsorizim",
    requestFeatured = "Kërkoni të Veçohet",
    manualPaymentNote = "Pagesat aktualisht procesohen manualisht. Do t'ju kontaktojmë brenda 24 orëve.",
    // Favorites
    myFavorites = "Të Preferuarat e Mia",
    noFavoritesYet = "Nuk keni ruajtur asnjë biznes ende.",
    myBusinesses = "Bizneset e Mia",
    noBusinessesYet = "Ende nuk keni asnjë biznes",
    noBusinessesYetSubtitle = "Shtoni biznesin tuaj për të arritur më shumë klientë",
    myBusinessesSubtitle = "Menaxhoni listimet e biznesit tuaj",
    myEvents = "Eventet e Mia",
    noEventsYet = "Ende nuk keni asnjë event",
    noEventsYetSubtitle = "Shtoni një event për të arritur më shumë njerëz",
    myEventsSubtitle = "Menaxhoni eventet tuaja të dërguara",
    deleteEvent = "Fshi Eventin",
    deleteEventConfirmTitle = "Fshi këtë event?",
    deleteEventConfirmMessage = "Kjo do ta heqë përgjithmonë eventin. Ky veprim nuk mund të zhbëhet.",
    eventDeleted = "Eventi u fshi",
    eventDeleteFailed = "Fshirja e eventit dështoi",
    noSearchResults = "Nuk u gjetën rezultate",
    upgradePremiumTitle = "Kalo në Premium",


    // In AlbanianStrings
    firstNameRequired = "Emri është i detyrueshëm",
    profileSaved = "Profili u ruajt!",
    profileSaveFailed = "Dështoi ruajtja e profilit",

    // In AlbanianStrings
    eventPhotoSection = "Foto e Ngjarjes (Opsionale)",
    eventDetailsSection = "Detajet e Ngjarjes",
    eventDateSection = "Data e Ngjarjes *",
    eventLocationSection = "Vendndodhja & Kontakti",

    eventTitleRequired = "Titulli i ngjarjes është i detyrueshëm",
    eventDescriptionRequired = "Përshkrimi është i detyrueshëm",
    eventLocationRequired = "Vendndodhja është e detyrueshme",
    eventInvalidDate = "Ju lutemi vendosni një datë të vlefshme",
    eventSubmitSuccess = "Ngjarja u dërgua me sukses!",
    eventSubmitFailed = "Dështoi dërgimi i ngjarjes",
    submitEventButton = "Dërgo Ngjarjen",

    writeReviewLabel = "Shkruaj vlerësimin tuaj",
    pleaseSelectRating = "Ju lutemi zgjidhni një vlerësim",
    pleaseWriteReview = "Ju lutemi shkruani një vlerësim",
    reviewSubmitted = "Vlerësimi u dërgua!",

    welcomeBack = "Mirësevini!",
    signInToContinue = "Hyni për të vazhduar",
    signUpToGetStarted = "Regjistrohu për të filluar",
    notNow = "Jo tani",

    emailRequired = "Email është i detyrueshëm",
    passwordRequired = "Fjalëkalimi është i detyrueshëm",
    passwordsDoNotMatch = "Fjalëkalimet nuk përputhen",
    passwordTooShort = "Fjalëkalimi duhet të ketë të paktën 8 karaktere",

    registerBusiness = "Regjistro Biznesin",
    requiredInformation = "Informacioni i Detyrueshëm",
    businessName = "Emri i Biznesit *",
    locationSection = "Vendndodhja *",
    fullAddress = "Adresa e Plotë *",
    cityLabel = "Qyteti *",
    countryLabel = "Shteti *",
    cityRequired = "Qyteti është i detyrueshëm",
    locatingAddress = "Duke gjetur koordinatat…",
    geocodeFailed = "Nuk u gjet ky adresë — ju lutem kontrolloni nëse është e saktë",
    latitude = "Gjerësia *",
    longitude = "Gjatësia *",
    pickLocationFromMap = "Zgjidhni Vendndodhjen nga Harta",
    contactInformation = "Informacioni i Kontaktit",
    phoneNumber = "Numri i Telefonit *",
    emailOptional = "Email (Opsional)",
    websiteOptional = "Faqja Web (Opsionale)",
    workingHoursSection = "Orari i Punës",
    open247 = "Hapur 24/7",
    photoOptional = "Foto (Opsionale)",
    photoAdded = "Foto u Shtua (1/1)",
    registering = "Duke Regjistruar...",
    registerBusinessButton = "Regjistro Biznesin",
    businessNameRequired = "Emri i biznesit është i detyrueshëm",
    selectCategory = "Ju lutemi zgjidhni një kategori",
    descriptionRequired = "Përshkrimi është i detyrueshëm",
    addressRequired = "Adresa është e detyrueshme",
    phoneRequired = "Numri i telefonit është i detyrueshëm",
    validCoordinates = "Ju lutemi vendosni koordinata të vlefshme",
    businessRegistered = "Biznesi u regjistrua me sukses!",
    cameraPermissionRequired = "Leja e kamerës është e nevojshme",
    gallery = "Galeria",
    camera = "Kamera",
    choosePhotoSource = "Zgjidhni burimin e fotos",

    // Generic dialog buttons
    ok = "OK",
    confirm = "Konfirmo",
    openButton = "Hap",

    // Time picker / working hours
    hoursOpenLabel = "Hapja",
    hoursCloseLabel = "Mbyllja",

    // Add Event date fields
    dayLabel = "Dita",
    dayPlaceholder = "DD",
    monthLabel = "Muaji",
    monthPlaceholder = "MM",
    yearLabel = "Viti",
    yearPlaceholder = "VVVV",
    eventStartTimeLabel = "Ora e fillimit",

    // Edit Business screen
    basicInformationSection = "Informacion Bazë",
    locationSectionShort = "Vendndodhja",
    saveChanges = "Ruaj Ndryshimet",
    businessUpdatedSuccess = "Biznesi u përditësua me sukses!",
    categoryRequiredLabel = "Kategoria *",
    descriptionRequiredLabel = "Përshkrimi *",
    photoLimitReached = "Limiti i fotove u arrit për planin tuaj",
    addJobPostingTitle = "Shto Vend Pune",
    jobTitleLabel = "Titulli i Punës *",
    jobTypeLabel = "Lloji i Punës *",
    jobSalaryLabel = "Paga (Opsionale)",
    jobSalaryPlaceholder = "p.sh. 1,500\$/muaj",
    addJobButton = "Shto Punë",
    jobTitleDescRequired = "Titulli dhe përshkrimi janë të detyrueshëm",
    addPromotionTitle = "Shto Promocion",
    promotionTitleLabel = "Titulli i Promocionit *",

    // Add Story screen
    addStoryTitle = "Shto Histori",
    addPhotosButton = "Shto Foto",
    captionPlaceholder = "Shkruani një përshkrim...",
    storyLocationPlaceholder = "p.sh. Tiranë, Shqipëri",
    postStory = "Posto Historinë",

    // Admin screen
    importSampleBusinesses = "Importo Biznese Shembull",
    approveClaimTitle = "Mirato Kërkesën",
    approveClaimMessage = "Jeni i sigurt që doni të miratoni kërkesën e %1\$s për \"%2\$s\"? Kjo do të transferojë pronësinë dhe do të verifikojë biznesin.",
    approve = "Mirato",
    rejectClaimTitle = "Refuzo Kërkesën",
    rejectClaimMessage = "Jeni i sigurt që doni të refuzoni këtë kërkesë nga %1\$s?",
    reject = "Refuzo",

    // Business detail screen
    writeReplyPlaceholder = "Shkruani një përgjigje...",
    noLocationSetToast = "Nuk ka vendndodhje të vendosur për këtë biznes",
    googleMapsNotInstalled = "Google Maps nuk është i instaluar",

    // Business list screen
    applyFilters = "Apliko Filtrat",
    allFilterOption = "Të gjitha",

    // Jobs screen
    viewProfile = "Shiko Profilin",
    jobsEmptyTitle = "Ende nuk ka vende pune",
    jobsEmptySubtitle = "Bizneset që po punësojnë do të shfaqen këtu",

    // Map / home screen
    appTagline = "Direktoria e Bizneseve Shqiptare",
    viewFullProfile = "Shiko Profilin e Plotë",
    noBusinessesNearYou = "Ende nuk ka biznese pranë jush",
    appGrowingMessage = "MeTont po rritet — kontrolloni përsëri së shpejti!",
    communityAnnouncements = "Njoftime të Komunitetit",
    noUpcomingEventsShort = "Nuk ka evente të ardhshme tani",
    mostFavoritedWorldwide = "Më të Preferuarit në Botë",
    noBusinessesYetHome = "Ende nuk ka biznese",

    // Story viewer
    viewBusiness = "Shiko Biznesin",
    couldntOpenMaps = "Nuk u hap dot harta",

    // Events screen
    couldntOpenLink = "Nuk u hap dot lidhja",

    // Reviews
    loginRequiredForReview = "Duhet të jeni të kyçur për të dërguar një vlerësim",

    // Subscription
    freeTierName = "Falas",

    // Edit Business screen (additional)
    editBusinessTitle = "Ndrysho Biznesin",
    savingLabel = "Duke ruajtur...",
    promotionsEmptyTitle = "Ende nuk ka promocione.",
    closedLabel = "Mbyllur",

    // Subscription screen (plan details)
    upgradeTitleTemplate = "Përmirëso \"%1\$s\"",
    subscriptionHeaderSubtitle = "Ndihmoni biznesin tuaj të dallohet në komunitetin shqiptar",
    perMonth = "në muaj",
    forever = "përgjithmonë",
    currentPlanButton = "Plani Aktual",
    notAvailableDash = "—",
    sendUpgradeRequest = "Dërgo kërkesën për përmirësim",
    sendFeaturedRequest = "Dërgo kërkesën për t'u veçuar",
    sendSponsorshipRequest = "Dërgo kërkesën për sponsorizim",
    planFeatureNameCategory = "Emri dhe kategoria e biznesit",
    planFeatureLocationOnMap = "Vendndodhja në hartë",
    planFeature100CharDesc = "Përshkrim 100 karaktere",
    planFeature1Photo = "1 foto",
    planFeaturePhoneNumber = "Numri i telefonit",
    planFeatureEmailWebsite = "Email dhe faqja web",
    planFeatureExtendedDesc = "Përshkrim i zgjeruar",
    planFeatureHoursOfOperation = "Orari i punës",
    planFeaturePremiumBadge = "Distinktivi Premium",
    planFeatureUp6Photos = "Deri në 6 foto",
    planFeatureEverythingPremium = "Gjithçka në Premium",
    planFeatureUp10Photos = "Deri në 10 foto",
    planFeatureFeaturedBadge = "Distinktivi i Veçuar",
    planFeatureFeaturedDiscoveryRow = "I veçuar në rreshtin e zbulimit",
    planFeatureHighlightedListView = "I theksuar në pamjen e listës",
    planFeatureUp14Photos = "Deri në 14 foto",
    planFeatureHighlightedMapPin = "Shenjë e theksuar në hartë",
    planFeatureTopSearchResults = "Në krye të rezultateve të kërkimit",
    planFeatureSponsoredBadge = "Distinktivi Sponsorizuar",
    planFeatureFeaturedDiscoverySection = "I veçuar në seksionin e zbulimit",
    planFeaturePriorityCustomerSupport = "Mbështetje klientësh me përparësi",

    // Admin screen (additional)
    pendingClaimRequests = "Kërkesat në Pritje",
    noPendingClaims = "Nuk ka kërkesa në pritje!",
    allClaimsProcessed = "Të gjitha kërkesat janë përpunuar.",
    pendingCountLabel = "në pritje",

    // Exception/error messages
    mustBeLoggedInToAddBusiness = "Duhet të jeni të kyçur për të shtuar një biznes",
    reviewNotFound = "Vlerësimi nuk u gjet",
    alreadyReportedReview = "E keni raportuar tashmë këtë vlerësim",
    replyNotFound = "Përgjigja nuk u gjet",
    reviewReportedSuccess = "Vlerësimi u raportua me sukses",
    failedToAddBusinessPrefix = "Shtimi i biznesit dështoi",
    failedToUploadImagesPrefix = "Ngarkimi i fotove dështoi",
    unexpectedErrorPrefix = "Gabim i papritur",
    failedToUploadPhotos = "Ngarkimi i fotove dështoi",
    failedToUpdateBusiness = "Përditësimi i biznesit dështoi",
    errorLoadingClaimsPrefix = "Gabim gjatë ngarkimit të kërkesave",
    failedToApprovePrefix = "Miratimi dështoi",
    failedToRejectPrefix = "Refuzimi dështoi",
    importFailedPrefix = "Importimi dështoi",
    claimApprovedTemplate = "Kërkesa u miratua — %1\$s tani i përket %2\$s",
    claimRejectedMsg = "Kërkesa u refuzua",
    importSuccessTemplate = "U importuan me sukses %1\$d biznese!",
    mustBeLoggedInToPostStory = "Duhet të jeni të kyçur për të postuar një histori",
    addAtLeastOnePhoto = "Ju lutemi shtoni të paktën një foto",
    maxPhotosPerStory = "Maksimumi 10 foto për histori",
    failedToPostStoryFallback = "Postimi i historisë dështoi",
    )

val LocalAppStrings = staticCompositionLocalOf { EnglishStrings }

// ViewModels and Repositories aren't Composables, so they can't read
// LocalAppStrings — there's no CompositionLocal context down there. This is a
// plain in-memory holder they can call instead (e.g. CurrentLanguage.strings().xxx)
// for the handful of app-authored exception/error messages that originate outside
// the UI layer. It's kept in sync with the real (Compose) language selection by
// ProvideAppStrings below, which every screen already sits under.
object CurrentLanguage {
    var language: AppLanguage = AppLanguage.EN
    fun strings(): AppStrings = if (language == AppLanguage.SQ) AlbanianStrings else EnglishStrings
}

@Composable
fun ProvideAppStrings(language: AppLanguage, content: @Composable () -> Unit) {
    CurrentLanguage.language = language
    val strings = if (language == AppLanguage.SQ) AlbanianStrings else EnglishStrings
    CompositionLocalProvider(LocalAppStrings provides strings) {
        content()
    }
}